export default Object.freeze({
  LOGIN: "Login",
  REGISTRATION: "Registration",
  HOMENAV: "HomeNav",
  HOME: "Home",
  PROFILE: "Profile",
  PROFILENAV: "ProfileNav",
  ITEMTOPNAV: "ItemTopNav",
  DETAILS: "Details",
  REVIEW: "Review",
  ADDTRAINING: "AddTraining",
  EDITTRAINING: "EditTraining",
  TRAININGITEMNAV: "TrainingItemNav",
  TRAININGITEM: "TrainingItem",
  MAIN: "Main",
  ALLTRAININGS: "AllTraining",
  ADDREVIEW: "AddReview",
});
